import numpy as np 
import pandas as pd 
import MLM.angle_between as angle
import MLM.moire_lattice_vector_finder as mlf 
from matplotlib.path import Path
from ase import Atoms
from ase.io import write


def read_vasp(file_path):
    lattice_vectors = {}
    lattice_vectors['a'] = np.loadtxt(file_path, skiprows=2, max_rows=1)
    lattice_vectors['b'] = np.loadtxt(file_path, skiprows=3, max_rows=1)
    lattice_vectors['c'] = np.loadtxt(file_path, skiprows=4, max_rows=1)
    atom_type = np.loadtxt(file_path, skiprows=5, max_rows=1, dtype='str')
    atom_counts = np.loadtxt(file_path, skiprows=6,max_rows=1, dtype = 'int')
    atom_type_arr = np.repeat(atom_type, atom_counts)
    data = np.loadtxt(file_path, skiprows = 8)
    
    return lattice_vectors, atom_type_arr, data

def replicate_atoms(a: np.array,
                    b: np.array,
                    c: np.array,
                    atom_data: np.array,
                    atom_type_arr: np.array,
                    natoms: int,
                    na: int,
                    nb: int,
                    nc: int):
    """ replicates given unit cell in -na to na and -nb to nb and nc 
    for purpose of moire structure creation
    and new lattice vectors which are na*a, nb*b, nc*c
    
    """ 
    
    replicated_atom = np.tile(atom_data,(((2 * na ) * ( 2 * nb ) * nc),1) )
    
    
    # Create displacement vectors for each replication
    displacements = np.array([
        ia * a +
        ib * b +
        ic * c
        for ia in range(-na, na )
        for ib in range(-nb, nb )
        for ic in range(nc)
    ])
    
        # Apply displacements to atom positions
    replicated_atom += np.repeat(displacements, natoms, axis=0)
    replicated_type_arr = np.tile(atom_type_arr,((2 * na  ) * ( 2 * nb ) * nc) )
    # new_a = a * na
    # new_b = b * nb 
    # new_c = c * nc
    new_lattice_vectors = {}
    new_lattice_vectors['a'] = a * na
    new_lattice_vectors['b'] = b * nb
    new_lattice_vectors['c'] = c * nc
    new_total_atoms = natoms * (2 * na ) * (2 * nb ) * nc
    return new_lattice_vectors, new_total_atoms, replicated_atom, replicated_type_arr

def select_atoms_in_polygon_path(df, polygon_path, tolerance):
    """
    Selects rows from a DataFrame where the 'x' and 'y' coordinates
    are inside or within a given tolerance of the specified polygon path.
    """
    xy_points = df[['x','y']].values  # Extract x, y coordinates
    # Add the radius parameter to include points near the boundary
    inside_mask = polygon_path.contains_points(xy_points, radius=tolerance)
    return df[inside_mask]

def write_vasp_optimized(filename, A1, A2, A3, atom_data, sort_order):
    # Buffer for all the lines to write
    element_type = " ".join(f"{key}" for key, _ in sort_order.items())
    element_count = " ".join(f"{len(sorted_df[sorted_df['type']==key])}" for key, _ in sort_order.items())
    lines = [
        "System Generated by MLM \n",
        "1.0\n",
        f"{A1[0]} {A1[1]} 0.0\n",
        f"{A2[0]} {A2[1]} 0.0\n",
        f"{A3[0]} {A3[1]} {A3[2]}\n",
        f"{element_type}\n",
        f"{element_count} \n",
        "Cartesian\n"
    ]
    atomic_positions = atom_data[['x', 'y', 'z']]
    # Write the buffer to the file
    with open(filename, 'w') as file:
        file.writelines(lines)
        # Use to_csv for efficient DataFrame writing
        atomic_positions.to_csv(file, sep=' ', index=False, header=False, mode='a')
        
def write_vasp_ase(filename, A1, A2, A3, atom_data):
    """
    Writes a VASP POSCAR file using the ASE library.

    Args:
        filename (str): Path to the output file.
        A1, A2, A3 (np.array): The three lattice vectors. A1 and A2 can be 2D.
        atom_data (pd.DataFrame): DataFrame with atom types and positions.
                                  Must contain 'type', 'x', 'y', and 'z' columns.
    """
    # 1. Ensure all lattice vectors are 3D to prevent shape errors.
    #    If A1 or A2 are 2D, add a z-component of 0.
    vec1 = np.array([*A1, 0.0]) if len(A1) == 2 else A1
    vec2 = np.array([*A2, 0.0]) if len(A2) == 2 else A2
    vec3 = np.array([*A3, 0.0]) if len(A3) == 2 else A3 # Also check A3 for robustness

    # 2. Combine the lattice vectors into a 3x3 cell matrix
    cell = np.array([vec1, vec2, vec3])

    # 3. Extract symbols and positions from the DataFrame
    symbols = atom_data['type'].tolist()
    positions = atom_data[['x', 'y', 'z']].values

    # 4. Create the ASE Atoms object
    # pbc=True sets periodic boundary conditions in all directions.
    atoms = Atoms(symbols=symbols, positions=positions, cell=cell, pbc=True)

    # 5. Write the file using ASE's VASP writer
    #    - format='vasp': Specifies the output format.
    #    - vasp5=True: Ensures VASP 5+ format (with element symbols).
    #    - sort=True: Sorts atoms by element type, replacing your sort_order logic.
    #    - direct=False: Writes coordinates in Cartesian format (the default).
    write(filename, atoms, format='vasp', vasp5=True, sort=True, direct=False)

def write_lammps_ase(filename, A1, A2, A3, atom_data):
    """
    Writes a LAMMPS data file using the ASE library.

    Args:
        filename (str): Path to the output file.
        A1, A2, A3 (np.array): The three lattice vectors. A1 and A2 can be 2D.
        atom_data (pd.DataFrame): DataFrame with atom types and positions.
                                  Must contain 'type', 'x', 'y', and 'z' columns.
    """
    # 1. Ensure all lattice vectors are 3D to prevent shape errors.
    vec1 = np.array([*A1, 0.0]) if len(A1) == 2 else A1
    vec2 = np.array([*A2, 0.0]) if len(A2) == 2 else A2
    vec3 = np.array([*A3, 0.0]) if len(A3) == 2 else A3

    # 2. Combine the lattice vectors into a 3x3 cell matrix
    cell = np.array([vec1, vec2, vec3])

    # 3. Extract symbols and positions from the DataFrame
    symbols = atom_data['type'].tolist()
    positions = atom_data[['x', 'y', 'z']].values

    # 4. Create the ASE Atoms object
    atoms = Atoms(symbols=symbols, positions=positions, cell=cell, pbc=True)

    # 5. Define the species order to ensure correct mass mapping
    unique_symbols = sorted(list(np.unique(symbols)))

    # 6. Write the file using ASE's LAMMPS writer
    #    - format='lammps-data': Specifies the output format.
    #    - atom_style='atomic': Sets the desired atom style.
    #    - specorder: Ensures correct mapping of atom types to masses.
    #    - masses=True: Explicitly tells the writer to include the Masses section.
    write(filename,
          atoms,
          format='lammps-data',
          atom_style='atomic',
          specorder=unique_symbols,
          masses=True)
